
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: {{ .Values.securityGroupRDS.name }}
  namespace: default
spec:
  description: {{ .Values.securityGroupRDS.description | quote }}
  vpcID: {{ .Values.vpcID | quote }}
  ingressRules:
    {{- range .Values.securityGroupRDS.ingressRules }}
    - fromPort: {{ .fromPort }}
      toPort: {{ .toPort }}
      ipProtocol: {{ .ipProtocol | quote }}
      userIDGroupPairs:
        - groupID: {{ .groupID | quote }}
          description: {{ .description | quote }}
    {{- end }}
  egressRules:
    - fromPort: 0
      toPort: 0
      ipProtocol: -1
      ipRanges:
        - cidrIP: "0.0.0.0/0"
          description: "Allow all outbound traffic"


---

apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: {{ .Values.rds.dbInstanceIdentifier }}
  namespace: default
spec:
  dbInstanceIdentifier: {{ .Values.rds.dbInstanceIdentifier | quote }}
  dbInstanceClass: {{ .Values.rds.dbInstanceClass | quote }}
  engine: {{ .Values.rds.engine | quote }}
  engineVersion: {{ .Values.rds.engineVersion | quote }}   # If you want to specify a specific engine version
  masterUsername: {{ .Values.rds.username | quote }}
  masterUserPassword:
    namespace: default
    name: rds-secret
    key: password
  allocatedStorage: {{ .Values.rds.allocatedStorage }}
  backupRetentionPeriod: {{ .Values.rds.backupRetentionPeriod }}
  publiclyAccessible: false
  multiAZ: true  # Example setting if you want high availability (optional)
  dbSubnetGroupName: {{ .Values.rds.subnetGroupName | quote }}
  vpcSecurityGroupIDs:
    - {{ .Values.securityGroupRDS.id | quote }}  # Ensure you are using the Security Group ID here
  storageType: "gp2"  # Example storage type (e.g., gp2 for general-purpose SSD)
  tags:   # Example tag settings
    - key: "environment"
      value: "production"
    - key: "team"
      value: "devops"
